const MAINNET_CHAIN_ID = 1;
const GOERLI_CHAIN_ID = 5;
const ARBITRUM_CHAIN_ID = 42161;

export const CHAIN_IDS = {
  MAINNET: MAINNET_CHAIN_ID,
  GOERLI: GOERLI_CHAIN_ID,
  ARBITRUM: ARBITRUM_CHAIN_ID,
};
