const projectConfig = {
  readyplayerme: {
    camera: { posZ: 0.48, lookY: 0.3 },
    rotation: { body: { x: 0.7 } },
  },
  XR: {
    rotation: {
      neck: {
        x: 0.2,
      },
    },
    blendshapes: {
      neck: {
        order: ['Z', 'Y', '-X'],
      },
    },
    bones: {
      BONE: 'Bone',
      HIPS: 'Hips',
      SPINE: 'Spine',
      SPINE_1: 'Chest',
      SPINE_2: 'Spine2',
      LEFT_SHOULDER: 'Left_shoulder',
      RIGHT_SHOULDER: 'Right_shoulder',
      LEFT_ARM: 'Left_arm',
      LEFT_FORE_ARM: 'Left_elbow',
      LEFT_HAND: 'Left_wrist',
      LEFT_THUMB_1: 'Thumb0_L',
      LEFT_THUMB_2: 'Thumb_1_L',
      LEFT_THUMB_3: 'Thumb2_L',
      LEFT_INDEX_1: 'Index_finger0_L',
      LEFT_INDEX_2: 'Index_finger1_L',
      LEFT_INDEX_3: 'Index_finger2_L',
      LEFT_MIDDLE_1: 'Middle_finger0_L',
      LEFT_MIDDLE_2: 'Middle_finger1_L',
      LEFT_MIDDLE_3: 'Middle_finger2_L',
      LEFT_RING_1: 'Ring_finger0_L',
      LEFT_RING_2: 'Ring_finger1_L',
      LEFT_RING_3: 'Ring_finger2_L',
      LEFT_PINKY_1: 'Little_finger0_L',
      LEFT_PINKY_2: 'Little_finger1_L',
      LEFT_PINKY_3: 'Little_finger2_L',
      RIGHT_ARM: 'Right_arm',
      RIGHT_FORE_ARM: 'Right_elbow',
      RIGHT_HAND: 'Right_wrist',
      RIGHT_THUMB_1: 'Thumb0_R',
      RIGHT_THUMB_2: 'Thumb_1_R',
      RIGHT_THUMB_3: 'Thumb2_R',
      RIGHT_INDEX_1: 'Index_finger0_R',
      RIGHT_INDEX_2: 'Index_finger1_R',
      RIGHT_INDEX_3: 'Index_finger2_R',
      RIGHT_MIDDLE_1: 'Middle_finger0_R',
      RIGHT_MIDDLE_2: 'Middle_finger1_R',
      RIGHT_MIDDLE_3: 'Middle_finger2_R',
      RIGHT_RING_1: 'Ring_finger0_R',
      RIGHT_RING_2: 'Ring_finger1_R',
      RIGHT_RING_3: 'Ring_finger2_R',
      RIGHT_PINKY_1: 'Little_finger0_R',
      RIGHT_PINKY_2: 'Little_finger1_R',
      RIGHT_PINKY_3: 'Little_finger2_R',
    },
  },
};

export { projectConfig };
